### PR TITLE
Add method to manually set the current sort option

### PR DESCRIPTION
**Pull request by adrian-stein**
Created method to manually set the sort option so on page load and not with a request I can change by default which sort is being used.

### CODE REVIEW

**Comment by markguinn** [comment]
Would you be able to squash these 3 commits into one?

**Comment by adrian-stein** [comment]
Done

**Comment by markguinn** [comment]
I don't think that actually worked - I now see 5 commits instead of 3. Did you run `git rebase -i HEAD~5`? You can just force push (`git push -f`) to this branch after that.

**Comment by adrian-stein** [comment]
I did git rebase -i HEAD~3 on the first 3 commits I had.

**Comment by adrian-stein** [comment]
How about now? I can only see 1 commit ?

**Comment by markguinn** [comment]
Perfect. Thanks!

**Pull request merged**
